# fly.toml

app = "zatbot"   # Debe coincidir con el nombre de tu app en Fly.io

[build]
  # puedes dejar vacío o especificar builder si quieres,
  # normalmente no hace falta tocar nada aquí.

# Define cómo Fly expone tu servidor
[[services]]
  internal_port = 5000   # ⇦ ESTE debe coincidir con tu PORT en index.js
  protocol     = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port     = 80        # Fly.io escucha en el 80 y lo redirige al 5000

  [[services.ports]]
    handlers = ["tls", "http"]
    port     = 443       # Para HTTPS si lo necesitas
