# fly.toml

app = "zatbot"    # Asegúrate de usar el nombre de tu app en Fly.io

[build]
  # puedes dejarlo vacío

[[services]]
  # Debe coincidir con el puerto de tu index.js (3000)
  internal_port = 3000
  protocol     = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port     = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port     = 443
