app = "zatbot"

# No necesitamos sección [build], Fly detectará el Dockerfile de forma automática.

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
